export const RULE_REASON_CODES = [
  "BANNED_CATEGORY",
  "CATEGORY_NOT_ALLOWLISTED",
  "REVIEW_CATEGORY_MAPPING",
  "MISSING_CATEGORY",
  "MISSING_SKU",
  "MISSING_REQUIRED_ATTRIBUTES",
  "MISSING_SUPPLIER_TRUST",
  "MISSING_SHIPPING_TIME",
  "MISSING_SHIPPING_METHOD",
  "MISSING_COST_DATA",
  "MISSING_FEE_MODEL",
  "MISSING_SHIPPING_ESTIMATE",
  "LOW_MARGIN",
  "BORDERLINE_MARGIN",
  "NEGATIVE_PROFIT",
  "BELOW_MINIMUM_ABSOLUTE_PROFIT",
  "LOW_SUPPLIER_TRUST",
  "LOW_STOCK_CONFIDENCE",
  "INVALID_STOCK_DATA",
  "WEAK_IMAGE_SET",
  "IMPROVE_DESCRIPTION",
  "LOW_DATA_QUALITY",
  "SHIPPING_TIME_EXCEEDS_THRESHOLD",
  "INVALID_PROJECTED_SALE_PRICE"
] as const;

export type RuleReasonCode = (typeof RULE_REASON_CODES)[number];
